// AUTO_GENERATED BY MVP Java Maven Plugin
package com.music.view.autogen;

import java.lang.Override;
import java.lang.String;

public enum FxmlEnum {
  REGISTRATION {
    @Override
    public String getFxmlFile() {
      return "/fxml/registration.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("registration.title");
    }
  };

  public abstract String getFxmlFile();

  public abstract String getTitle();

  public String getStringFromResourceBundle(String key) {
    return java.util.ResourceBundle.getBundle("Bundle").getString(key);
  }
}
